export inst_count=0x110000000
export BASE=YOUR_PATH
export RVGCC=${BASE}/riscv-toolchain/bin/riscv64-unknown-linux-gnu-
export SPECPATH=/opt/cpu2017/benchspec/CPU

mkdir 525_${1}
cp enclave.c $SPECPATH/525.x264_r/src/
cd $SPECPATH/525.x264_r/src/

cp x264_src/x264.c x264_src/x264_new.c
if [ ${1} = "vault" ]; then
# sed -i "1a #include \"enclave.c\"" main_new.c
sed -i "152a _EncStart();" x264_src/x264_new.c
# sed -i "153a printf(\"Hello wxr\");" x264_src/x264_new.c
fi

${RVGCC}gcc -std=c99   -march=rv64imafdc -c -o enclave.o -DSPEC -DNDEBUG -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP -D INST_COUNT=${inst_count} -g -O3 -march=rv64imafdc -flto -ffast-math -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon -DSPEC_LP64 enclave.c

${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/predict.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/predict.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/mc.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/mc.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/macroblock.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/macroblock.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/pixel.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/pixel.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/cpu.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/cpu.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/frame.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/frame.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/cabac.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/cabac.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/mdate.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/mdate.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/dct.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/dct.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/rectangle.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/rectangle.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/common.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/common.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/set.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/set.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/quant.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/quant.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/vlc.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/vlc.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/deblock.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/deblock.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/common/mvpred.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/common/mvpred.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/set.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/set.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/me.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/me.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/ratecontrol.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/ratecontrol.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/macroblock.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/macroblock.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/cabac.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/cabac.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/cavlc.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/cavlc.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/lookahead.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/lookahead.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/input/timecode.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/input/timecode.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/input/yuv.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/input/yuv.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/input/y4m.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/input/y4m.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/output/raw.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/output/raw.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/output/matroska.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/output/matroska.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/encoder.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/encoder.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/output/matroska_ebml.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/output/matroska_ebml.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/encoder/analyse.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/encoder/analyse.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/output/flv.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/output/flv.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/output/flv_bytestream.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/output/flv_bytestream.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/input/thread.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/input/thread.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/extras/getopt.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/extras/getopt.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc -c -o x264_src/x264.o -DSPEC -DNDEBUG -Ildecod_src/inc -Ix264_src -Ix264_src/extras -Ix264_src/common -DSPEC_AUTO_SUPPRESS_OPENMP -DSPEC_AUTO_BYTEORDER=0x12345678  -g -O3 -march=rv64imafdc -flto -ffast-math         -fno-strict-aliasing -fno-unsafe-math-optimizations -fno-finite-math-only -fgnu89-inline -fcommon     -DSPEC_LP64  x264_src/x264_new.c
${RVGCC}gcc     -std=c99   -march=rv64imafdc      -g -O3 -march=rv64imafdc -flto -ffast-math    enclave.o     x264_src/common/mc.o x264_src/common/predict.o x264_src/common/pixel.o x264_src/common/macroblock.o x264_src/common/frame.o x264_src/common/dct.o x264_src/common/cpu.o x264_src/common/cabac.o x264_src/common/common.o x264_src/common/mdate.o x264_src/common/rectangle.o x264_src/common/set.o x264_src/common/quant.o x264_src/common/deblock.o x264_src/common/vlc.o x264_src/common/mvpred.o x264_src/encoder/analyse.o x264_src/encoder/me.o x264_src/encoder/ratecontrol.o x264_src/encoder/set.o x264_src/encoder/macroblock.o x264_src/encoder/cabac.o x264_src/encoder/cavlc.o x264_src/encoder/encoder.o x264_src/encoder/lookahead.o x264_src/input/timecode.o x264_src/input/yuv.o x264_src/input/y4m.o x264_src/output/raw.o x264_src/output/matroska.o x264_src/output/matroska_ebml.o x264_src/output/flv.o x264_src/output/flv_bytestream.o x264_src/input/thread.o x264_src/x264.o x264_src/extras/getopt.o             -lm         -o x264_r  

cp x264_r ../data/refrate/input/*  ${BASE}/programs/SPEC/525_${1}
rm *.o x264_r
